//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace НамордникDesktop.Scripts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductView
    {
        public int ID { get; set; }
        public string ProdTitle { get; set; }
        public string PtodType { get; set; }
        public string Article { get; set; }
        public string Descr { get; set; }
        public string Image { get; set; }
        public Nullable<int> PersonCount { get; set; }
        public Nullable<int> WorkshopNum { get; set; }
        public decimal MinCost { get; set; }
    }
}
